In [23]:
import pandas as pd
from sklearn import neighbors, model_selection, metrics, preprocessing, pipeline
import numpy as np

In [6]:
df = pd.read_excel('UniversalBank.xls', sheet_name='Data')

In [7]:
df.head()

ID  Age  Experience  Income  ZIP Code  Family  CCAvg  Education  Mortgage  \
0   1   25           1      49     91107       4    1.6          1         0   
1   2   45          19      34     90089       3    1.5          1         0   
2   3   39          15      11     94720       1    1.0          1         0   
3   4   35           9     100     94112       1    2.7          2         0   
4   5   35           8      45     91330       4    1.0          2         0   

   Personal Loan  Securities Account  CD Account  Online  CreditCard  
0              0                   1           0       0           0  
1              0                   1           0       0           0  
2              0                   0           0       0           0  
3              0                   0           0       0           0  
4              0                   0           0       0           1

In [30]:
target = df['Personal Loan']
dataset = df.drop(['Personal Loan', 'ID', 'ZIP Code'], axis=1)

cat_features = ['Education']
cat_feature_index = np.array([(feature in cat_features) for feature in dataset.columns], dtype=bool)

x_train, x_val, y_train, y_val = model_selection.train_test_split(dataset,
                                                                 target,
                                                                  test_size=0.4)

super_ml_pipe = pipeline.Pipeline(steps=[
    ('Some_preprocessing', pipeline.FeatureUnion(transformer_list=[
        ('Cat_feature', pipeline.Pipeline(steps=[
            ('Selecting', preprocessing.FunctionTransformer(lambda data: data[:,cat_feature_index], validate=True)),
            ('hot_encoding', preprocessing.OneHotEncoder(handle_unknown='ignore'))
        ]))
    ])),
    ('ML', neighbors.KNeighborsClassifier(n_neighbors=1))
])

In [31]:
super_ml_pipe.fit(x_train, y_train)

Pipeline(memory=None,
         steps=[('Some_preprocessing',
                 FeatureUnion(n_jobs=None,
                              transformer_list=[('Cat_feature',
                                                 Pipeline(memory=None,
                                                          steps=[('Selecting',
                                                                  FunctionTransformer(accept_sparse=False,
                                                                                      check_inverse=True,
                                                                                      func=<function <lambda> at 0x7f297d718950>,
                                                                                      inv_kw_args=None,
                                                                                      inverse_func=None,
                                                                                      kw_args=None,
                              

## A

In [36]:
test_object = pd.DataFrame({
    'Age':[40],
    'Experience':[10],
    'Income':[84],
    'Family':[2],
    'CCAvg':[2],
    'Edacation':[2],
    'Mortgage':[0],
    'Securities Account':[0],
    'CD Account':[0],
    'Online':[1],
    'CreditCard':[1]
})

super_ml_pipe.predict(test_object)[0]

0

## B

In [64]:
grid = {'ML__n_neighbors': np.arange(1, 50)}

super_ml_pipe = pipeline.Pipeline(steps=[
    ('Some_preprocessing', pipeline.FeatureUnion(transformer_list=[
        ('Cat_feature', pipeline.Pipeline(steps=[
            ('Selecting', preprocessing.FunctionTransformer(lambda data: data[:,cat_feature_index], validate=True)),
            ('hot_encoding', preprocessing.OneHotEncoder(handle_unknown='ignore'))
        ]))
    ])),
    ('ML', neighbors.KNeighborsClassifier())
])
cv = model_selection.GridSearchCV(super_ml_pipe, grid, scoring='roc_auc')


In [65]:
cv.fit(x_train, y_train)

/home/mightyracoon/.local/lib/python3.7/site-packages/sklearn/model_selection/_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


GridSearchCV(cv='warn', error_score='raise-deprecating',
             estimator=Pipeline(memory=None,
                                steps=[('Some_preprocessing',
                                        FeatureUnion(n_jobs=None,
                                                     transformer_list=[('Cat_feature',
                                                                        Pipeline(memory=None,
                                                                                 steps=[('Selecting',
                                                                                         FunctionTransformer(accept_sparse=False,
                                                                                                             check_inverse=True,
                                                                                                             func=<function <lambda> at 0x7f297c423bf8>,
                                                                           

In [66]:
print('Ответ: {0}'.format(cv.best_estimator_.get_params()['ML__n_neighbors']))

Ответ: 24


## C

In [67]:
preds = cv.best_estimator_.predict(x_val)
print(metrics.confusion_matrix(y_val, preds))

[[1804    0]
 [ 196    0]]


Хорошо обучился метод...

## D

In [70]:
test_object = pd.DataFrame({
    'Age':[40],
    'Experience':[10],
    'Income':[84],
    'Family':[2],
    'CCAvg':[2],
    'Edacation':[2],
    'Mortgage':[0],
    'Securities Account':[0],
    'CD Account':[0],
    'Online':[1],
    'CreditCard':[1]
})
cv.best_estimator_.predict(test_object)[0]

0

In [72]:
x_train, x, y_train, y = model_selection.train_test_split(dataset,
                                                         target,
                                                         test_size=0.5)

x_val, x_test, y_val, y_test = model_selection.train_test_split(x, y, test_size=0.4)

In [73]:
super_ml_pipe = pipeline.Pipeline(steps=[
    ('Some_preprocessing', pipeline.FeatureUnion(transformer_list=[
        ('Cat_feature', pipeline.Pipeline(steps=[
            ('Selecting', preprocessing.FunctionTransformer(lambda data: data[:,cat_feature_index], validate=True)),
            ('hot_encoding', preprocessing.OneHotEncoder(handle_unknown='ignore'))
        ]))
    ])),
    ('ML', neighbors.KNeighborsClassifier(n_neighbors=24))
])

In [74]:
super_ml_pipe.fit(x_train, y_train)

Pipeline(memory=None,
         steps=[('Some_preprocessing',
                 FeatureUnion(n_jobs=None,
                              transformer_list=[('Cat_feature',
                                                 Pipeline(memory=None,
                                                          steps=[('Selecting',
                                                                  FunctionTransformer(accept_sparse=False,
                                                                                      check_inverse=True,
                                                                                      func=<function <lambda> at 0x7f297c316840>,
                                                                                      inv_kw_args=None,
                                                                                      inverse_func=None,
                                                                                      kw_args=None,
                              

Conf matrix for train

In [75]:
preds = cv.best_estimator_.predict(x_train)
print(metrics.confusion_matrix(y_train, preds))

[[2288    0]
 [ 212    0]]


Conf matrix for validaation

In [76]:
preds = cv.best_estimator_.predict(x_val)
print(metrics.confusion_matrix(y_val, preds))

[[1334    0]
 [ 166    0]]


conf matrix for test

In [77]:
preds = cv.best_estimator_.predict(x_test)
print(metrics.confusion_matrix(y_test, preds))

[[898   0]
 [102   0]]
